#include "Background.h"
#include "ImageLoading.h"
#include <iostream>
#include <fstream>
#include <string>
static const unsigned int s_MapWidth = 30;

/*static const char* s_MapTiles =
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
"DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED"
;*/

Background::Background()
{
	m_TexName = 0;
	m_MapWidth = 0;
	m_MapHeight = 0;
}

void Background::loadBackground(std::string file, float tileSizeX, float tileSizeY)
{

	//load png image
	int imageHeight = 0;
	int imageWidth = 0;

	//create the texture on the GPU
	glGenTextures(1, &m_TexName);
	glBindTexture(GL_TEXTURE_2D, m_TexName);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);  //or use GL_CLAMP
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);

	bool success = ImageLoading::loadImage(file);
	if (!success) {
		std::cout << "Unable to load image file" << std::endl;
		glDeleteTextures(1, &m_TexName);
		return;
	}
	else
	{
		std::cout << "Image loaded " << std::endl;
	}
	static std::string s_MapTiles;
	std::string line;
	std::ifstream myReadFile;

	myReadFile.open("src/example.txt");
	if (myReadFile.is_open())
	{
		while (std::getline(myReadFile, line))
		{
			s_MapTiles += line;
		}
	}
	else
	{
		std::cout << "CAN'T OPEN FILE";
	}
	Tile dirt(0.0f, 0.0f, 0, 8, 128.0f, 128.0f,2304.0f, 2304.0f, m_TexName);
	Tile track(0.0f, 0.0f, 4, 7, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);
	Tile topEnd(0.0f, 0.0f, 5, 7, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);
	Tile rightEnd(0.0f, 0.0f, 4, 8, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);
	Tile bottomEnd(0.0f, 0.0f, 3, 7, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);
	Tile leftEnd(0.0f, 0.0f, 4, 6, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);

	Tile topLeft(0.0, 0.0, 5, 9, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);
	Tile topRight(0.0, 0.0, 5, 10, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);
	Tile bottomLeft(0.0, 0.0, 4, 9, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);
	Tile bottomRight(0.0, 0.0, 4, 10, 128.0f, 128.0f, 2304.0f, 2304.0f, m_TexName);

	m_TileLookup.emplace('B', dirt);
	m_TileLookup.emplace('T', track);
	m_TileLookup.emplace('W', topEnd);
	m_TileLookup.emplace('A', leftEnd);
	m_TileLookup.emplace('S', bottomEnd);
	m_TileLookup.emplace('D', rightEnd);

	m_TileLookup.emplace('Q', topLeft);
	m_TileLookup.emplace('R', topRight);
	m_TileLookup.emplace('Z', bottomLeft);
	m_TileLookup.emplace('V', bottomRight);


	m_MapWidth = 30;
	std::cout << s_MapTiles.length();
	m_MapHeight = s_MapTiles.length() / s_MapWidth;
	for (unsigned int y = 0; y < m_MapHeight; y++)
	{
		for (unsigned int x = 0; x < m_MapWidth; x++)
		{
			char tileType = s_MapTiles[x + (y * m_MapWidth)];
			if (m_TileLookup.find(tileType) != m_TileLookup.end())
			{
				Tile temp = m_TileLookup[tileType];
				tiles[x + (y * m_MapWidth)] = temp;
				//std::cout << "inserting dirt";
			}
			else
			{
				std::cout << "can't find texture";
				tiles[x + (y * m_MapWidth)] = dirt;
			}
		}
	}
}

unsigned int Background::GetMapWidth()
{
	return m_MapWidth;
}
unsigned int Background::GetMapHeight()
{
	return m_MapHeight;
}